### ISSUE TITLE
Request for Windows App

### ISSUE THREAD

**Issue by ceebu** [thebigg73/OpenSongTablet#111]
First off - thank you for this app - I have been using this app for more than 2 years and it had save me hours of manual effort with paper lyrics - So thanks for your time and energy in doing this.

Hi, I currently use OpenSong on Windows to edit lyrics and sync using dropbox to keep my tab synced with the lyrics. My Challenge is that when I link a backing track to a lyrics, further syncing from my PC overwrites the existing lyrics and so I use to link only the specific set that I need, just before my program.  And I do this every time i perform.

Am not sure if what i want can be achieved using existing features - if there's a way to make it work, please let me know. If there's not, then it would be great to have a windows app version (or a web app version), that I could use to link the tracks from my PC and have it be synced up on my tab.

**Comment by iv-gha** [comment]
You can add songs to a set as song variations.  Since 5.4.2 you can open the song you want and long press '+'.  You can long press the song icon to transpose.

The song variation is part of the set.  You can change it any way you want - it does not affect the original song.  It will not get overwritten by your sync.

To 'keep' the song variations you save the set.  Loading a saved set will make any song variations in contains available again (the lyrics etc. as at when you saved).  The original song does not have to be on your device.

Different sets can have different song variations - load a set to get that version.

If you want to make a song variation 'normal' you can use song>duplicate to save it into a folder.

Might help.
