### ISSUE TITLE
Network type may not be being verified in method

### ISSUE THREAD

**Issue by amazuerar** [thebigg73/OpenSongTablet#127]
Dear Developer!

My name is Alejandro Mazuera-Rozo, I am a PhD Student at Universidad de los Andes, and at Università della Svizzera italiana. I am part of a research on the usage of network libraries within android apps. As a result of this we identified that there is a missing validation of network type within a method since some network operations are being performed in it. As you might know, a device can have various types of network connections. For the full list of possible network types, see https://developer.android.com/reference/android/net/ConnectivityManager. Therefore it is recommended for the app to identify the type of network available before performing a network operation.

Note: `Wi-Fi` is typically faster. Also, mobile data is often metered, which can get expensive. A common strategy for apps is to only fetch large data if a Wi-Fi network is available.

In order to address this issue we recommend you to visit:

1. https://developer.android.com/training/basics/network-ops/managing
2. https://developer.android.com/training/efficient-downloads/connectivity_patterns

**Potential Code Location without Network type validation**

https://github.com/thebigg73/OpenSongTablet/blob/8563eeeab9745b42c67e1ab7c779b92fcdf4bf28/app/src/main/java/com/garethevans/church/opensongtablet/PopUpCustomSlideFragment.java#L574-L577

Related issues: #125

**Comment by thebigg73** [comment]
Many thanks for alerting me to this.
This issue is addressed in an upcoming version that is still in early alpha. Since this branch will be superseded, I have decided not to fix in this branch, but leave until the new version.

https://github.com/thebigg73/OpenSongTablet/blob/3e0c70441fac363a737b1aa87ac3dfc54610443a/app/src/main/java/com/garethevans/church/opensongtablet/appdata/CheckInternet.java#L23-L48
