### ISSUE TITLE
Internet availability may not be being verified in method

### ISSUE THREAD

**Issue by amazuerar** [thebigg73/OpenSongTablet#128]
Dear Developer!

My name is Alejandro Mazuera-Rozo, I am a PhD Student at Universidad de los Andes, and at Università della Svizzera italiana. I am part of a research on the usage of network libraries within android apps. As a result of this we have identified some code locations that might have a missing validation of Internet availability, validation that is needed since some network operations are being performed within some methods.

As you might know, a device may be connected to a network but may not have Internet connection. Therefore it is recommended for the app to identify whether the device is connected to a network having Internet connectivity before performing a network operation.

In order to address this issue we recommend you to visit:

1. https://developer.android.com/reference/android/net/NetworkCapabilities
2. https://developer.android.com/reference/android/net/NetworkCapabilities#NET_CAPABILITY_INTERNET
3. https://developer.android.com/reference/android/net/NetworkCapabilities#NET_CAPABILITY_VALIDATED

**Potential Code Location missing Internet connectivity validation:**

https://github.com/thebigg73/OpenSongTablet/blob/8563eeeab9745b42c67e1ab7c779b92fcdf4bf28/app/src/main/java/com/garethevans/church/opensongtablet/DownloadTask.java#L49-L56

Related issues: #121

**Comment by thebigg73** [comment]
Many thanks for alerting me to this.
This issue is addressed in an upcoming version that is still in early alpha.   Since this branch will be superseded, I have decided not to fix in this branch, but leave until the new version.

https://github.com/thebigg73/OpenSongTablet/blob/3e0c70441fac363a737b1aa87ac3dfc54610443a/app/src/main/java/com/garethevans/church/opensongtablet/appdata/CheckInternet.java#L23-L48

**Comment by thebigg73** [comment]
[](url)
