### ISSUE TITLE
Song duration not saving.

### ISSUE THREAD

**Issue by millerthegorilla** [thebigg73/OpenSongTablet#23]
I am often finding that when I am returning to my songs, the duration of the songs has been lost.  I know the songs are stored in XML rather than database, so is there something that I need to do to save the edited song, so that I don't lose the changes that I've made?
Also, it would be nice to be able to add a couple of buttons or a slider, to speed or slow the song duration, editing and saving the new song duration as the change occurred at the button/slider.
I haven't had time to look at the code with regards to converting it to Linux yet, but I might do this weekend if I get time.  If I make any useful changes I'll submit a pull request.
Thanks for all your good work!

**Comment by thebigg73** [comment]
I suspect that this value isn't saved if you click on the start button rather than clicking on the tick to save.  I've updated the code to save the duration when clicking on start.
Regarding the slider/buttons, do you mean on the autoscroll popup window?  I can't really add a slider as this would limit the maximum song length to whatever I set the slider size to be.  If buttons, do you mean a '+' and a '-' button?

**Comment by millerthegorilla** [comment]
I've just pushed some changes, but yh, I mean to add a fragment that would have a slider.  The slider fragment is a fixed size and just increases and decreases the speed, in the same way a + and - button might.  The + and - button might be easier, but I thought it might be good to be able to increase the song duration by a variable amount of seconds each time the slider is adjusted, with the slider returning to the middle, a bit like a pitch wheel on a synth.
