### ISSUE TITLE
v6 beta - page scroll

### ISSUE THREAD

**Issue by iv-gha** [thebigg73/OpenSongTablet#237]
v5 has on screen page scroll buttons, when 'disabled' the button areas remain active giving the user an area (no button visible) to click for scroll.  For v6 performance only, can we have large hidden active areas over the bottom third(ish) and top third(ish) of the song for scroll.  The central area would still support screen gestures.  This is to aid usability.  Please consider.

**Comment by thebigg73** [comment]
This would have to be optional and it could cause issue with users with devices set to use gesture navigation instead of Android navigation bar.

**Comment by iv-gha** [comment]
I am confused.  An app having buttons causes navigation problems?  v5 has
these now, albeit smaller active areas...  what are the issues?

**Comment by thebigg73** [comment]
If a user presses near the bottom of the screen, the bottom navigation bar can be shown (if in full screen).  This can cause issues with overlapping buttons, with one or the other being activated. 
There is also the issue of potential overlap with the prev/next buttons, which I want to keep.  These are more useful in my opinion than invisible scroll areas that can be effected by normal scrolling, page buttons or pedals.
I've worked up a better solution using hot zones - fully customisable actions rather than the v5 ones.  They are set to the top centre, bottom centre and top left of the screen. 

https://www.opensongapp.com/user-manual/controls/hot-zones

**Comment by thebigg73** [comment]
Actually, I was thinking of swipe controls in those zones - ignore my
comments of navigation.
The issue of prev/next, which are staying may still be an issue - however,
it is impossible to have everything visible on a small screen and still
expect no issue of fitting it all on without overlaps!
Please check my implemented fix.

**Comment by iv-gha** [comment]
Yes, this adds the v5 behaviour with increased flexibility.  I think the feature should default to active and be set to scroll as this is what v5 does OOBE.

**Comment by iv-gha** [comment]
It is great to have a performance screen configured with no buttons displayed and be able to scroll - and nothing else happen!

Apologies for the run around getting to this - it ends up being very similar in design to the scroll areas in v5 which I could have detailed better.  These were made active even when the button was off a while back - hopefully we've had no complaints. 
 Perhaps because it is sensible behaviour.

I see in v6 they are not present when not in use - great.  v5 is scroll specific so areas are only active if relevant.  You can see them being added and removed a little after the scroll if you have layout bounds display turned on.

Kind regards
Ian

**Comment by iv-gha** [comment]
I have spotted that the top left short press action is not being saved - on restart it is lost.

**Comment by thebigg73** [comment]
Oops - forgot that I changed the name of the save variable when testing.  Fixed
Added auto hide if scroll up/down not required due to position of current scroll (only if zones are scroll specific with no alternative short/long press actions)
Set scroll down/up to default centre hot zones
