### ISSUE TITLE
Set variations actually affect the original copy

### ISSUE THREAD

**Issue by ZsigE** [thebigg73/OpenSongTablet#24]
Hi! Just found what I think is a bug in the set variations function - this has been happening since the graphical redesign. To reproduce:
1. Clear the set and create a new one
2. Add a few songs to the new set
3. Make a set item variation for one of the songs in the middle of the set. It shows up properly in the set list as a variation.
4. Edit it in some way - transpose it a couple of keys, for instance
5. Navigate to a different song in the set, then go back to the edited one. Might take a couple of attempts for the bug to show up.
6. The song appears to be unedited (e.g. in the original key).

What I think has happened is that the variation copy has been created but isn't in the navigation system, so swiping from earlier songs in the list actually gets you to the original (even though it's marked as the variation in the list). If you go through the filesystem to get to the "variation" copy, you can see it's unedited.
 
(Thanks again for all the work you put into this app, it's fantastic. I'm using a Lenovo Tab2 A10 running Marshmallow, if that helps.)

**Comment by thebigg73** [comment]
Thanks for pointing this one out.
The issue was the after creating the variation and updating the set, the new song filename and folder location weren't being saved into the preferences.  When any edit action was carried out it loads the preferences to get the song filename and folder, so was loading and editing the original!
If you created a variation and then navigated away from this song, then back, the issue wouldn't happen.

Added a fix in my current live version (hoping to update here soon)
