### ISSUE TITLE
Tabs messed up

### ISSUE THREAD

**Issue by hohwille** [thebigg73/OpenSongTablet#62]
I tried to follow this guide:
https://www.opensongapp.com/user-guide/songs/using-guitar-tab

However, when I entered something like:
```
#[My Tabs]
;e -------------4-
;B -5-5-4-5-7-7---
```
It is still not displayed monospaced.
Further it is automatically converted to:
```
#[My Tabs]
{c:;e -------------4-}
{c:;B -5-5-4-5-7-7---}
```
After saving the song once more it is entirely messed up as:
```
#[My Tabs]
{comments:;e -------------4-}
{comments:;B -5-5-4-5-7-7---}
```

I am using `ChordPro` mode in case this makes any difference.

**Comment by thebigg73** [comment]
Yes, the page you refer to only applies for tabs entered in OpenSong format mode.
You also need the vertical line, otherwise the app won't recognise it as tab.  Should be:
;e |--------4

The format of tab lines is a semi colon so that the desktop app and protection years it as a comment) followed by the string tuning note (followed by a space if it is a single character), then a vertical line | then the tab itself.

This is because the app thinks the your tab lines are just comments, so it gives it the Chordpro comment field {c:....} This is the short comment tag which is the same as {comment:.....}.

It is the missing vertical line that is causing your problem.

On testing this, there is a big in transferring backwards and forwards between OpenSong and chordpro format that I'll need to look at.  It seems to combine tab lines.  Also spotted that chord lines without words underneath get stripped out and deleted.

For now, if you want to add tab, you'll need to keep it in OpenSong format.  I'm heading off on holiday today for a week, so it will need to wait until I return.

**Comment by hohwille** [comment]
When I do so, I got the tabs displayed correctly.
However, when I then edit the songe once more, the entire tab is gone.
I spent hours listening to the song in order to figure out the tabs and all my work is gone.
There is IMHO no history to the song and undo after saving to the previous saving is not possible.

**Comment by thebigg73** [comment]
I think I've figured out the issue here (assuming that the issue described is when changing between OpenSong/ChordPro formatting).  I will apply this fix to the next update (hopefully coming out today).
You are right that there is no song history when editing, however, this will be the case in the upcoming MaterialApp version.
Apologies for any inconvenience and for forgetting about this fix.
